# Generated by Django 3.2 on 2021-04-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Hikayenin Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Hikaye İçeriği')),
                ('image', models.ImageField(default='memories/default.jpg', upload_to='memories/&Y/%m/%d/')),
                ('date', models.DateTimeField(verbose_name='Hikaye Tarihi')),
                ('available', models.BooleanField(default=True, verbose_name='Hikaye Aktif Mi?')),
            ],
        ),
    ]
