# Generated by Django 3.2 on 2021-04-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20210429_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(default='memories/default.jpg', upload_to='memories/%Y/%m/%d/'),
        ),
    ]
