# Generated by Django 3.2 on 2021-05-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_name', models.CharField(max_length=200, unique=True, verbose_name='Ülkenin Adı')),
                ('future_image', models.ImageField(default='memories/default.jpg', upload_to='memories/%Y/%m/%d/')),
                ('future_date', models.DateField(verbose_name='Planlanan Tarih')),
                ('future_okey', models.BooleanField(default=False, verbose_name='Gidildi Mi?')),
            ],
        ),
    ]
